name: Chrme

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter code'
        required: true
      pincode:
        description: 'Six digit Pin'
        default: '123456'
        required: true
      go:
        description: 'Wait 250 min & upload Downloads?'
        required: true
        type: boolean
        default: false
  
jobs:
  build:
    runs-on: Windows-latest

    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v4

    - name: 'Set up Python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 'Install Python dependencies'
      run: pip install requests requests-toolbelt tqdm
    
    - name: 'Initializing Setup'
      run: ./setup.ps1
      shell: pwsh
      
    - name: 'Starting CRD'
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
      shell: pwsh

    - name: 'Wait 250 min and Upload Downloads'
      # This step only runs if you checked the 'go' box
      if: github.event.inputs.go == true
      # Pass the secrets securely into the script's environment
      shell: pwsh
      run: |
        Write-Host "Wait & Upload mode selected."
        Write-Host "Waiting 250 minutes (15000 seconds)..."
        Start-Sleep -Seconds 15000
        
        Write-Host "Wait finished. Zipping and uploading Downloads folder..."
        cd "C:\Users\runneradmin\Downloads"
        
        # We call the python script from its original location in the repo
        python $Env:GITHUB_WORKSPACE\me.py . -zdd
        
        Write-Host "Upload process complete."

    - name: 'Keep Alive (360 min)'
      # This step only runs if you did NOT check the 'go' box
      if: github.event.inputs.go == false
      run: ./mother.ps1
      shell: pwsh
