name: macOS Remote Desktop (CRD)

on:
  workflow_dispatch:
    inputs:
      crd_auth_code:
        description: 'Paste ONLY the auth code, not the full command'
        required: true
      pin_code:
        description: '6-digit PIN for the connection'
        default: '123456'
        required: true

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: 1. Install Dependencies
        run: |
          echo "Installing Google Chrome and CRD Host via Homebrew..."
          brew install --cask google-chrome
          brew install --cask chrome-remote-desktop-host
      
      - name: 2. Debug - Find Package Location
        id: debug_path
        run: |
          echo "--- Running brew info to see installation details ---"
          brew info --cask chrome-remote-desktop-host
          
          echo "--- Exploring the Caskroom directory ---"
          # The standard location for Cask installations
          CASK_DIR="/usr/local/Caskroom
