name: macOS Remote Desktop (CRD)

on:
  workflow_dispatch:
    inputs:
      crd_auth_code:
        description: 'Paste ONLY the auth code, not the full command'
        required: true
      pin_code:
        description: '6-digit PIN for the connection'
        default: '123456'
        required: true
      user_password:
        description: 'Set a password for the new remote desktop user'
        default: 'PleaseChangeMe'
        required: true

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: 1. Install Dependencies
        run: |
          echo "Installing Google Chrome and downloading the CRD Host installer..."
          brew install --cask google-chrome
          brew install --cask chrome-remote-desktop-host
      
      - name: 2. Create a New User Account
        run: |
          echo "Creating a new user account for the RDP session..."
          sudo dscl . -create /Users/rdpuser
          sudo dscl . -create /Users/rdpuser UserShell /bin/bash
          sudo dscl . -create /Users/rdpuser RealName "RDP User"
          sudo dscl . -create /Users/rdpuser UniqueID "1001"
          sudo dscl . -create /Users/rdpuser PrimaryGroupID 80
          sudo dscl . -create /Users/rdpuser NFSHomeDirectory /Users/rdpuser
          sudo dscl . -passwd /Users/rdpuser "${{ github.event.inputs.user_password }}"
          sudo createhomedir -c -u rdpuser
          sudo dscl . -append /Groups/admin GroupMembership rdpuser
          
      - name: 3. Manually Unpack and Configure CRD
        id: unpack_crd
        run: |
          echo "--- Manually unpacking the .pkg file to bypass installer issues ---"
          PKG_PATH=$(find /usr/local/Caskroom/chrome-remote-desktop-host -name "*.pkg" | head -n 1)
          if [[ -z "$PKG_PATH" ]]; then
            echo "::error::Could not find the downloaded .pkg file." && exit 1
          fi
          echo "Found installer at: $PKG_PATH"

          mkdir crd_extracted
          pkgutil --expand "$PKG_PATH" crd_extracted
          (cd crd_extracted && gunzip -c Payload | cpio -i)
          
          CRD_EXEC_PATH=$(find "$(pwd)/crd_extracted" -name "remoting_start_host" | head -n 1)
          if [[ -z "$CRD_EXEC_PATH" ]]; then
            echo "::error::Could not find remoting_start_host after unpacking." && exit 1
          fi

          echo "✅ Successfully unpacked executable to: $CRD_EXEC_PATH"
          echo "CRD_EXEC_PATH=$CRD_EXEC_PATH" >> $GITHUB_ENV

      - name: 4. Start Chrome Remote Desktop Host
        run: |
          echo "Starting CRD Host as the new user..."
          # Run the command as the newly created user
          sudo -u rdpuser "${{ env.CRD_EXEC_PATH }}" \
            --code="${{ github.event.inputs.crd_auth_code }}" \
            --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
            --name=GitHub-macOS-Runner \
            -pin=${{ github.event.inputs.pin_code }} &
            
      - name: 5. Display Info and Keep Alive
        run: |
          sleep 15
          echo "✅ Your session should be ready!"
          echo "--------------------------------------------------------"
          echo "Connect at: https://remotedesktop.google.com/access"
          echo "The runner will appear as 'GitHub-macOS-Runner'."
          echo "PIN: ${{ github.event.inputs.pin_code }}"
          echo "---"
          echo "If prompted for system credentials inside the session, use:"
          echo "User: rdpuser"
          echo "Password: ${{ github.event.inputs.user_password }}"
          echo "--------------------------------------------------------"
          echo "Session is active. This job will time out in ~6 hours."
          echo "To end the session, cancel the GitHub Actions workflow."
          sleep 21600
