name: MacCRD
on:
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD Auth Code'
        required: true
      pincode:
        description: 'Six digit Pin'
        default: '123456'
        required: true
jobs:
  build:
    name: MacCRD
    runs-on: macos-latest

    steps:
    - name: Setup Chrome Remote Desktop
      run: |
        brew install --cask chrome-remote-desktop-host
        /Applications/Chrome\ Remote\ Desktop\ Host.app/Contents/MacOS/remoting_start_host --code="${{ github.event.inputs.authcode }}" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=MacCRD -pin=${{ github.event.inputs.pincode }}

    - name: Keep Alive
      run: |
        echo "Remote desktop is running. You can connect now."
        sleep 3600 # Keep the instance alive for 1 hour
