name: MacCRD
on:
  workflow_dispatch:

jobs:
  build:
    name: MacCRD
    runs-on: macos-latest

    steps:
    - name: Tailscale
      uses: tailscale/github-action@v4
      with:
       oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
       oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
       tags: tag:p
    - name: Setup Chrome Remote Desktop
      run: |
        brew tap LizardByte/homebrew
        brew install sunshine
        brew services start lizardbyte/homebrew/sunshine

    - name: Keep Alive
      run: |
        echo "Remote desktop is running. You can connect now."
        sleep 3600 # Keep the instance alive for 1 hour
