name: MacCRD
on:
  workflow_dispatch:

jobs:
  build:
    name: MacCRD
    runs-on: macos-latest

    steps:
    - name: Tailscale
      uses: tailscale/github-action@v4
      with:
       oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
       oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
       tags: tag:p
    - name: Setup Chrome Remote Desktop
      run: |
        sudo mdutil -i off -a
        #Create new account
        sudo dscl . -create /Users/runneradmin
        sudo dscl . -create /Users/runneradmin UserShell /bin/bash
        sudo dscl . -create /Users/runneradmin RealName Runner_Admin
        sudo dscl . -create /Users/runneradmin UniqueID 1001
        sudo dscl . -create /Users/runneradmin PrimaryGroupID 80
        sudo dscl . -create /Users/runneradmin NFSHomeDirectory /Users/tcv
        sudo dscl . -passwd /Users/runneradmin P@ssw0rd!
        sudo dscl . -passwd /Users/runneradmin P@ssw0rd!
        sudo createhomedir -c -u runneradmin > /dev/null
        sudo dscl . -append /Groups/admin GroupMembership runneradmin
        brew tap LizardByte/homebrew
        brew install sunshine
        brew services start lizardbyte/homebrew/sunshine

    - name: Keep Alive
      run: |
        echo "Remote desktop is running. You can connect now."
        sleep 3600 # Keep the instance alive for 1 hour
